In [9]:
import numpy as np

# 1. Create a random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original array:\n", arr)

# 2. Reshape the array to 3x5
arr = arr.reshape(3, 5)
print("\nReshaped array (3x5):\n", arr)

# 3. Print the shape of the array
print("\nShape of array:", arr.shape)

# 4. Replace the max in each row with 0
for i in range(arr.shape[0]):
    max_index = arr[i].argmax()
    arr[i][max_index] = 0

print("\nArray after replacing max in each row with 0:\n", arr)

Original array:
 [ 8 19  6 11  7  4 16  1 13 13 15  5 16 14  8]

Reshaped array (3x5):
 [[ 8 19  6 11  7]
 [ 4 16  1 13 13]
 [15  5 16 14  8]]

Shape of array: (3, 5)

Array after replacing max in each row with 0:
 [[ 8  0  6 11  7]
 [ 4  0  1 13 13]
 [15  5  0 14  8]]


In [10]:
import numpy as np

# Create a 4x3 array of 4-byte integers (int32)
a = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# Print array
print("Array:\n", a)

# Print shape
print("\nShape:", a.shape)

# Print type of the object
print("Type:", type(a))

# Print data type of the elements
print("Data Type:", a.dtype)

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


In [11]:
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print results
print("Eigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [12]:
b = np.array([[0, 1, 2],
                [3, 4, 5]])

#Sum of diagonal elements
sum_diagonal = np.sum(np.diagonal(b))

print("Sum of diagonal elements:", sum_diagonal)


Sum of diagonal elements: 4


In [5]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

# Reshape it to 2x3
reshaped_arr = arr.reshape(2, 3)

print("Original array (3x2):")
print(arr)

print("\nReshaped array (2x3):")
print(reshaped_arr)

Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
